### ISSUE TITLE
HightlightText

### ISSUE THREAD

**Issue by Keys01** [ahausladen/PdfiumLib#47]
I am trying to Hightlight two texts in a pdf.

     TextoLocal.Add('Casa');
     TextoLocal.Add('Coche');

      if Texto.Count > 0  then
       begin
        for var i := 0 to textoLocal.Count - 1 do
         PDFVisual.HightlightText(textoLocal[i], false, false);
       end;

 TextoLocal is a TStringList;
 PDfVisual is a TPdfControl;

But it only Hightlight the second text

**Comment by ahausladen** [comment]
I've added a new method `AddHighlightText` that can be used to add multiple texts. In order to remove the highlighted texts you must call `ClearHighlightText`, otherwise the highlighted texts will become more and more.

The older HighlightText() method keeps backward compatibility by always clearing the highlighted texts before adding a single new one.

```Delphi
PDFVisual.ClearHighlightTest;
for var i := 0 to TextoLocal.Count - 1 do
  PDFVisual.AddHightlightText(TextoLocal[i], false, false);
```
